Hw10 motion sensor
luzhnov-aleksei/home_work_basic pull request #9
Opened 2024-07-26 08:48 UTC by luzhnov-aleksei

2024-07-26 11:50 UTC, vladislavmass requested changes

2024-07-26 11:50 UTC, hungry-honeybadger commented on hw10_motion_sensor/main.go
> +				mid := float32(storage/depth) + 0.5
Поясните зачем тут +0.5

2024-07-26 11:50 UTC, hungry-honeybadger commented on hw10_motion_sensor/main.go
> +				c <- int(r.Int64())
Такая реализация приводит к тому, что не соблюдается гарантия работы того, что код работает равно delay времени. Данная реализация создает возможность управлять временем работы из читающий из канала горутины. Пример данной проблемы можно посмотреть вот по этой ссылке `https://go.dev/play/p/Y7iRql2foxB`

2024-07-26 12:00 UTC, luzhnov-aleksei commented on hw10_motion_sensor/main.go
> +				mid := float32(storage/depth) + 0.5
для корректного округления, чтобы например 2.6 округлялся до 3

2024-07-26 12:03 UTC, hungry-honeybadger commented on hw10_motion_sensor/main.go
> +				mid := float32(storage/depth) + 0.5
Для этого есть math.Ceil()

2024-07-27 08:22 UTC, vladislavmass approved these changes

2024-09-26 18:38 UTC, merged